name: PROD Deploy Web
on:
  workflow_dispatch:
    inputs:
      confirm:
        required: true
        description: Please type "production".
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  issues: write

env:
  APP_VERSION: ${{ github.ref_name }}

jobs:
  deploy:
    if: github.event.action == 'published' || github.event.inputs.confirm == 'production'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context, null,2))
            console.log(JSON.stringify(github, null,2))
            console.log(JSON.stringify(core, null,2))
