name: PROD Deploy Web
on:
  workflow_dispatch:
    inputs:
      confirm:
        required: true
        description: Please type "production".
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: read
  issues: write

env:
  APP_VERSION: ${{ github.ref_name }}

jobs:
  deploy:
    if: github.event.action == 'published' || github.event.inputs.confirm == 'production'
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(JSON.stringify(context, null,2))
            console.log(JSON.stringify(github, null,2))
            console.log(JSON.stringify(core, null,2))

            const actor = context.actor;

            let issueTitle = "";
            let issueBody = "";

            switch(context.eventName) {
              case "release":
                issueTitle = `:rocket: Release ${ context.payload.release.name }`;
                issueBody = `${ context.payload.release.body }
            - ${ context.payload.release.html_url }`;
                break;
              case "workflow_dispatch":
                issueTitle = ":ambulance: Manual Deploy ${{ github.ref_name }}";
                issueBody = `## 確認事項
            - [ ] :warning: 本番環境に対して手動でのデプロイを実施します。
            - [ ] デプロイ対象のタグ: **${{ github.ref_name }}**`;
                break;
            }
            console.log({issueTitle})
            console.log({issueBody})
